Update all dependencies in rust bitcoin ecosystem
stevenroose/hal pull request #24
Opened 2021-03-08 02:44 UTC by sanket1729

Hi @stevenroose, 
   I was not aware of this project until Andrew mentioned it to be last week. I have updated all the dependencies to the latest releases. 

There were a lot of changes in rust-miniscript, there is a big diff. Another commit adds more features from rust-miniscript. Over the next weekend, I will add support for xpub descriptors. 

I also want to add a command to the psbt module something like:

`signrawpsbt <psbt> <index> <list_priv_keys>` that would signed psbt.

2021-03-13 20:17 UTC, stevenroose commented
Thanks! I've been having a hard time contemplating useful miniscript commands because I didn't really know the APIs (they also seem to have changed a lot). So very happy to have you add some!

Can you remove the Cargo.lock commit? Since this is a binary project, it's supposed to be included (please also commit changes to it in the commit that updates the dependencies), so that the build doesn't break when dependencies change.

2021-03-13 20:21 UTC, stevenroose requested changes
Other than Cargo.lock and some nits, this looks good! Thanks!

2021-03-13 20:21 UTC, stevenroose commented on src/bin/hal/cmd/miniscript.rs
> +		    non_malleable: ScriptContexts::from_bare(ms.is_non_malleable()),
some indentation here

2021-03-13 20:21 UTC, stevenroose commented on src/bin/hal/cmd/miniscript.rs
> +		    non_malleable: ScriptContexts::from_p2sh(ms.is_non_malleable()),
indentation

2021-03-13 20:21 UTC, stevenroose commented on src/bin/hal/cmd/miniscript.rs
> +		    non_malleable: ScriptContexts::from_segwitv0(ms.is_non_malleable()),
indentation

2021-03-13 20:21 UTC, stevenroose commented on Cargo.toml
> +tiny-bip39 = "0.8.0"
I'm planning to use the bip39 crate here soon (as soon as v1.0.0 releases), so feel free to revert this.

2021-03-13 22:44 UTC, sanket1729 commented
Ready for review again

2021-03-15 11:19 UTC, stevenroose approved these changes
LGTM, thanks!

2021-03-15 11:19 UTC, merged

2021-03-15 11:21 UTC, stevenroose commented
> I also want to add a command to the psbt module something like:
> 
> signrawpsbt <psbt> <index> <list_priv_keys> that would signed psbt.

About that, yeah that and finalizepsbt were 2 commands I really wanted but needed miniscript features to actually fulfill. Would be awesome if you could add them once miniscript supports them!